// math-test-prompts.js
// Four separate feedback arrays for the math test game.
// Put this file BEFORE your main script.js file in the HTML.

const encouragingCorrect = [
    "You got it!",
    "Nice! You're figuring these out.",
    "That one looked easy for you.",
    "You're doing really well.",
    "Good job! Keep it going.",
    "You're getting faster.",
    "That was a smart answer.",
    "You've got the hang of this.",
    "Nice work!",
    "You knew that one right away.",
    "You're making good progress.",
    "You should feel good about that one.",
    "That's another one right.",
    "You're thinking carefully.",
    "That was a good solve.",
    "You're getting into a rhythm.",
    "You've been making good choices.",
    "You're doing better than you probably think.",
    "Way to stay focused.",
    "That answer was spot on.",
    "You're improving as you go.",
    "That was quick.",
    "You didn't overthink it.",
    "Keep answering them like that.",
    "You've got good math skills.",
    "You're making this look easier.",
    "That was the right move.",
    "You're staying locked in.",
    "You've got this.",
    "You're doing awesome.",
    "Great thinking.",
    "Nice job catching that.",
    "You're on a roll.",
    "Keep trusting yourself.",
    "You solved that perfectly.",
    "Excellent work.",
    "That answer was right on.",
    "You're staying sharp.",
    "That's exactly right.",
    "Nice! One more down.",
];

const encouragingWrong = [
    "That's okay. Try the next one.",
    "Don't worry, everyone misses some.",
    "You were close. Keep going.",
    "Shake it off and stay focused.",
    "One wrong answer doesn't ruin the test.",
    "Take your time on the next one.",
    "You can still turn this around.",
    "That one was tricky.",
    "Keep your head in it.",
    "You're still doing fine.",
    "Don't let that one mess with you.",
    "The next problem is a fresh start.",
    "Keep trying. You've got more chances.",
    "That happens. Move on to the next.",
    "You don't have to be perfect.",
    "Stay calm and keep working.",
    "You're still learning as you go.",
    "That's okay. You'll get the next one!",
    "Think it through and keep going.",
    "You can bounce back from that.",
    "Missing one is normal.",
    "Don't give up now.",
    "You're capable of getting the next one.",
    "That was just one question.",
    "You've gotten others right before.",
    "Slow down a little and trust yourself.",
    "You're still in this.",
    "Try not to rush the next one.",
    "Good effort. Keep going.",
    "That was a hard one to catch.",
    "You can recover from that.",
    "Stay with it.",
    "You're doing better than you feel.",
    "Mistakes help you see what to fix.",
    "You've still got time.",
    "Keep thinking carefully.",
    "Next one. You've got it.",
];

const discouragingCorrect = [
    "You got it... but that one was obvious.",
    "Even I knew that answer.",
    "That one was easy. Treyson could even do it.",
    "Don't get excited. That was easy.",
    "About time you got one.",
    "That doesn't prove anything.",
    "You barely got that.",
    "Let's see if you can do it again.",
    "One right answer doesn't mean much.",
    "That one was basically free.",
    "Anybody could've answered that.",
    "You're celebrating that?",
    "That wasn't impressive.",
    "You finally got one.",
    "I expected you to get that one.",
    "That's the easiest question so far.",
    "You should've answered that faster.",
    "It took you long enough.",
    "Don't think you're suddenly good at math.",
    "You're still going to miss the next one.",
    "That wasn't hard.",
    "You almost messed that one up.",
    "You looked confused the whole time.",
    "You're lucky that wasn't harder.",
    "That answer was handed to you.",
    "Even guessing would've worked there.",
    "You're acting like that was difficult.",
    "That doesn't make up for the others.",
    "You've still got a long way to go.",
    "I wouldn't celebrate yet.",
    "Most kids would get that right.",
    "That's nothing special.",
    "You only got it because it was simple.",
    "You should expect to get those right.",
    "That wasn't exactly impressive.",
    "You've got a lot more to prove.",
    "I'll be surprised if you get the next one.",
    "Let's see how long that lasts.",
    "Don't let one answer fool you.",
];

const discouragingWrong = [
    "Seriously? That was the answer you picked?",
    "You're doing terrible dude.",
    "Come on, that wasn't even a hard one.",
    "I knew you were going to miss that.",
    "You're making this look way harder than it is.",
    "How did you get that wrong?",
    "Do you even know math?",
    "You need to actually think before answering.",
    "That was not even close.",
    "You're guessing, aren't you?",
    "This is why you need to pay attention.",
    "You just gave away another point.",
    "Everyone else would probably be ahead by now.",
    "That answer made no sense.",
    "You're missing the easy ones now.",
    "You're getting worse as this goes on.",
    "That was painful to watch.",
    "Do you even know what you're doing?",
    "You're making simple math look impossible.",
    "I thought you would at least get that one.",
    "OH MY GOSH, Treyson could answer that question!",
    "You're not helping your score at all.",
    "You really picked that answer?",
    "You're going to run out of questions at this rate.",
    "Maybe slow down, because this isn't working.",
    "That one should have been automatic.",
    "You're acting like you've never seen math before.",
    "You're giving yourself no chance.",
    "That was a terrible answer.",
    "I don't know how you got that.",
    "You're getting destroyed by this test.",
    "You're making yourself look bad. You should stop.",
    "That mistake was on you.",
    "That was easy! How do you keep missing these?",
    "You're digging yourself into a hole.",
    "You're not locked in at all.",
    "You're making the score worse every time.",
    "At this point, I expected that.",
];

// Optional helper function.
// Your game can use this to pick a random message from any array.
function getRandomPrompt(promptArray) {
    return promptArray[Math.floor(Math.random() * promptArray.length)];
}
